// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (status)
VALUES ($1)
RETURNING id, status, created_at, updated_at
`

func (q *Queries) CreateEpisode(ctx context.Context, status string) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode, status)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM
episodes WHERE id = $1
`

func (q *Queries) DeleteEpisode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEpisode, id)
	return err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, status, created_at, updated_at
FROM episodes
WHERE id = $1
`

func (q *Queries) GetEpisode(ctx context.Context, id pgtype.UUID) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT id, status, created_at, updated_at
FROM episodes
ORDER BY created_at DESC
`

func (q *Queries) ListEpisodes(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisodeStatus = `-- name: UpdateEpisodeStatus :one
UPDATE episodes
SET
    status = ($2),
    updated_at = NOW()
WHERE id = ($1)
RETURNING id, status, created_at, updated_at
`

type UpdateEpisodeStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateEpisodeStatus(ctx context.Context, arg UpdateEpisodeStatusParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisodeStatus, arg.ID, arg.Status)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
