// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    episode_id,
    event_type,
    payload
)
VALUES ($1, $2, $3)
RETURNING id, episode_id, event_type, payload, created_at
`

type CreateEventParams struct {
	EpisodeID pgtype.UUID
	EventType string
	Payload   []byte
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.EpisodeID, arg.EventType, arg.Payload)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeEvents = `-- name: GetEpisodeEvents :many
SELECT id, episode_id, event_type, payload, created_at
FROM events
WHERE episode_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetEpisodeEvents(ctx context.Context, episodeID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEpisodeEvents, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
