// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Episode struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Event struct {
	ID        pgtype.UUID
	EpisodeID pgtype.UUID
	EventType string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type Participant struct {
	ID               pgtype.UUID
	EpisodeID        pgtype.UUID
	OrganizationName string
	ParticipantType  string
	ContactName      pgtype.Text
	Email            pgtype.Text
	Phone            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
